[package]
name = "wasmcloud"
version = "0.1.0"
edition = "2021"
authors = ["The wasmCloud Team"]
license = "Apache-2.0"
categories = ["wasm"]
description = "wasmCloud Host Runtime"
repository = "https://github.com/wasmCloud/wasmCloud"

[badges.maintenance]
status = "actively-developed"

[dependencies]
anyhow = { workspace = true }
futures = { workspace = true, features = ["std"] }
log = { workspace = true, optional = true }
rand = { workspace = true, features = ["std"], optional = true }
tokio = { workspace = true, features = ["fs", "macros", "rt"], optional = true }
tracing = { workspace = true, features = ["release_max_level_info"] }
tracing-subscriber = { workspace = true, features = ["ansi", "env-filter", "fmt", "json", "std"], optional = true }
uuid = { workspace = true }
wascap = { workspace = true }
wasmbus-rpc = { workspace = true }
wasmcloud-interface-logging = { workspace = true }
wasmcloud-interface-numbergen = { workspace = true }
wasmtime = { workspace = true, features = ["async", "cache", "cranelift", "jitdump", "parallel-compilation", "pooling-allocator", "vtune"] }
wasmtime-wasi = { workspace = true, features = ["sync"] }

[features]
default = ["bin", "component-model", "log", "rand"]
bin = ["log", "tracing-subscriber", "rand", "tokio"]
component-model = ["wasmtime/component-model"]
log = ["dep:log", "tracing/log"]

[build-dependencies]
cbindgen = { workspace = true }

[dev-dependencies]
actor-echo-module = { workspace = true }
actor-http-log-rng-component = { workspace = true }
actor-http-log-rng-module = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["fs", "macros", "rt"] }
tracing-subscriber = { workspace = true, features = ["ansi", "env-filter", "fmt", "json", "std"] }
wasmcloud-interface-httpserver = { workspace = true }
wat = { workspace = true }
wit-component = { workspace = true }

[workspace.dependencies]
actor-echo-module = { path = "./tests/actors/echo-module", target = "wasm32-unknown-unknown", artifact = "cdylib" }
actor-http-log-rng-component = { path = "./tests/actors/http-log-rng-component", target = "wasm32-unknown-unknown", artifact = "cdylib" }
actor-http-log-rng-module = { path = "./tests/actors/http-log-rng-module", target = "wasm32-unknown-unknown", artifact = "cdylib" }
anyhow = { version = "1.0.69", default-features = false }
cbindgen = { version = "0.24.3", default-features = false }
futures = { version = "0.3.26", default-features = false }
log = { version = "0.4.17", default-features = false }
once_cell = { version = "1.17.1", default-features = false }
rand = { version = "0.8.5", default-features = false }
serde = { version = "1.0.152", default-features = false }
serde_json = { version = "1.0.93", default-features = false }
tokio = { version = "1.26.0", default-features = false }
tracing = { version = "0.1.37", default-features = false }
tracing-subscriber = { version = "0.3.16", default-features = false }
uuid = { version = "1.3.0", default-features = false }
wascap = { version = "0.10.0", default-features = false }
wasmbus-rpc = { version = "0.11.2", default-features = false }
wasmcloud = { path = "." }
wasmcloud-example-runner = { version = "0.4.0", default-features = false }
wasmcloud-interface-httpserver = { version = "0.9.0", default-features = false }
wasmcloud-interface-logging = { version = "0.8.1", default-features = false }
wasmcloud-interface-numbergen = { version = "0.8.1", default-features = false }
wasmtime = { version = "6.0.0", default-features = false }
wasmtime-wasi = { version = "6.0.0", default-features = false }
wat = { version = "1.0.61", default-features = false }
wit-bindgen = { version = "0.4.0", default-features = false }
wit-component = { version = "0.7.4", default-features = false }
