[package]
name = "wasmcloud-provider-httpserver"
version = "0.17.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
atty = { workspace = true }
base64 = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
http = { workspace = true }
opentelemetry = { workspace = true, features = ["rt-tokio"] }
serde_bytes = { workspace = true }
serde_json = { workspace = true }
serde = {workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
warp = { workspace = true, features=["tls"] }
wasmcloud-interface-httpserver = { workspace = true }
wasmbus-rpc = { workspace = true, features = ["otel"] }

[dev-dependencies]
assert_matches = { workspace = true }
blake2 = { workspace = true }
reqwest = { workspace = true, features = ["json", "rustls-tls"] }
wasmcloud-test-util = { workspace = true }
wasmcloud-provider-httpserver = { path = ".", artifact = "bin" }

[lib]
name = "wasmcloud_provider_httpserver"
path = "src/lib.rs"

[[bin]]
name = "httpserver"
path = "bin/main.rs"
