[package]
name = "wasmcloud-provider-httpclient"
version = "0.6.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
atty = { workspace = true }
base64 = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
crossbeam = { workspace = true }
futures = { workspace = true }
once_cell = { workspace = true }
reqwest = { workspace = true, features = ["rustls-tls"] }
rmp-serde = { workspace = true }
serde_bytes = { workspace = true }
serde_json = { workspace = true }
serde = {workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

wasmcloud-interface-httpclient = { workspace = true }
wasmbus-rpc = { workspace = true, features = ["otel"] }

# test dependencies
[dev-dependencies]
wasmcloud-test-util = { workspace = true }

[[bin]]
name = "httpclient"
path = "src/main.rs"
