name: install Nix

inputs:
  cachixAuthToken:
    description: auth token for https://app.cachix.org/organization/wasmcloud/cache/wasmcloud

env:
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 1 # abort caching attempt if it's slow

runs:
  using: composite
  steps:
  # Install Nix
  - uses: DeterminateSystems/nix-installer-action@v2
    with:
      extra-conf: |
        accept-flake-config = true

  # Setup Cachix cache
  - uses: cachix/cachix-action@v12
    continue-on-error: true
    with:
      name: wasmcloud
      authToken: '${{ inputs.cachixAuthToken }}'
