name: install Nix

inputs:
  cachixAuthToken:
    description: auth token for https://app.cachix.org/organization/wasmcloud/cache/wasmcloud

env:
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 1 # abort caching attempt if it's slow

runs:
  using: composite
  steps:
  - run: sudo mkdir -p /nix
    if: ${{ runner.os == 'Linux' }}
    shell: bash
  - run: sudo chown $(whoami) /nix
    if: ${{ runner.os == 'Linux' }}
    shell: bash
  - uses: actions/cache@v3
    if: ${{ runner.os == 'Linux' }}
    with:
      path: /nix
      key: nix
  - uses: DeterminateSystems/nix-installer-action@v2
    with:
      extra-conf: |
        accept-flake-config = true
  - uses: cachix/cachix-action@v12
    continue-on-error: true
    with:
      name: wasmcloud
      authToken: '${{ inputs.cachixAuthToken }}'
