[package]
name = "blobby"
version = "0.4.0"
authors = ["wasmCloud Team"]
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "blobby"

[dependencies]
anyhow = "1"
form_urlencoded = "1.2"
http = "1.1"
wit-bindgen = "0.22"

[profile.release]
# Optimize for small code size
lto = true
opt-level = "s"
strip = true
