[package]
name = "wasmcloud-provider-kv-vault"
description = "Hashicorp Vault capability provider for the wasmcloud KeyValue capability contract wasmcloud:keyvalue"
authors = [ "wasmcloud Team" ]
version = "0.3.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/wasmcloud/capability-providers"
publish = false

[dependencies]
async-trait = { workspace = true }
atty = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["sync", "rt"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
url = { workspace = true }
vaultrs = { workspace = true }
wasmcloud-interface-keyvalue = { workspace = true }
wasmbus-rpc = { workspace = true, features = ["otel"] }

# test dependencies
[dev-dependencies]
rand = { workspace = true }
env_logger = { workspace = true }
wasmcloud-test-util = { workspace = true }
wasmcloud-provider-kv-vault = { path = ".", artifact = "bin" }

[build-dependencies]
# for local code generation of wasmbus-interface-keyvalue
weld-codegen = { workspace = true }

[[bin]]
name = "kv-vault"
path = "src/main.rs"


[lib]
name = "kv_vault_lib"
path = "src/lib.rs"
