[package]
name = "wasmcloud-provider-lattice-controller"
description = "Capability provider that allows actors to interact with lattice control interfaces"
version = "0.10.1"
edition = "2021"

[dependencies]
async-nats = { workspace = true }
async-trait = { workspace = true }
atty = { workspace = true }
base64 = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
once_cell = { workspace = true }
rmp-serde = { workspace = true }
serde_bytes = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
wascap = { workspace = true }
wasmbus-rpc = { workspace = true, features = ["otel"] }
wasmcloud-control-interface = { workspace = true }
wasmcloud-interface-lattice-control = { workspace = true }

# test dependencies
[dev-dependencies]
wasmcloud-test-util = { workspace = true }

[[bin]]
name = "lattice-controller"
path = "src/main.rs"
