[package]
name = "wasmcloud-provider-nats"
version = "0.16.3"
edition = "2021"

[dependencies]
async-nats = { workspace = true }
async-trait = { workspace = true }
atty = { workspace = true }
base64 = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
crossbeam = { workspace = true }
futures = { workspace = true }
once_cell = { workspace = true }
rmp-serde = { workspace = true }
serde_bytes = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
toml = { workspace = true }
tracing = { workspace = true }
tracing-futures = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
wascap = { workspace = true }
anyhow = { workspace = true }

wasmbus-rpc = { workspace = true, features = [ "otel" ] }
wasmcloud-interface-messaging = { workspace = true }

# test dependencies
[dev-dependencies]
wasmcloud-provider-nats = { path = ".", artifact = "bin" }
wasmcloud-test-util = { workspace = true }

[[bin]]
name = "nats_messaging"
path = "src/main.rs"
