[package]
name = "wasmcloud-provider-blobstore-s3"
version = "0.3.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
atty = { workspace = true }
aws-sdk-s3 = { workspace = true }
aws-config = { workspace = true }
aws-types = { workspace = true, features = ["hardcoded-credentials"] }
aws-smithy-http = { workspace = true }
aws-smithy-types = { workspace = true }
base64 = { workspace = true }
bytes = { workspace = true }
http = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
serde_bytes = { workspace = true }
serde_json = { workspace = true }
serde = {workspace = true, features = ["derive"] }
simple_env_load = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-stream = { workspace = true }
tokio-util = { workspace = true, features = ["io"] }
toml = { workspace = true }
tracing = { workspace = true }
tracing-futures = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
wasmbus-rpc = { workspace = true, features = ["otel"] }

# test dependencies
[dev-dependencies]
rand = { workspace = true }
fastrand = { workspace = true }
crc32fast = { workspace = true }
env_logger = { workspace = true }
wasmcloud-test-util = { workspace = true }
wasmcloud-interface-blobstore = { workspace = true }
wasmcloud-interface-testing = { workspace = true }

[build-dependencies]
weld-codegen = { workspace = true }

[lib]
name = "blobstore_s3_lib"
path = "src/lib.rs"

[[bin]]
name = "blobstore-s3"
path = "src/main.rs"
