[package]
name = "wasmcloud-provider-sqldb-postgres"
version = "0.4.0"
description = "Postgres SQL Database capability provider for contract wasmcloud:sqldb"
readme = "README.md"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
atty = { workspace = true }
base64 = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
minicbor = { workspace = true, features = ["derive", "std", "half"] }
once_cell = { workspace = true }
rmp-serde = { workspace = true }
serde_bytes = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-postgres = { workspace = true, features = ["with-bit-vec-0_6", "with-chrono-0_4","with-uuid-1", "with-eui48-0_4"] }
bb8-postgres = { workspace = true }
bit-vec = { workspace = true }
uuid = { workspace = true }
native-tls = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
wasmbus-rpc = { workspace = true, features = [ "otel" ] }
wasmcloud-interface-sqldb = { workspace = true }

# test dependencies
[dev-dependencies]
wasmcloud-test-util = { workspace = true }

[[bin]]
name = "sqldb-postgres"
path = "src/main.rs"
