[package]
name = "wasmcloud-provider-kvredis"
version = "0.19.1"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
atty = { workspace = true }
base64 = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
crossbeam = { workspace = true }
futures = { workspace = true }
once_cell = { workspace = true }
redis = { workspace = true, features = ["tokio-comp", "aio", "connection-manager"] }
rmp-serde = { workspace = true }
serde_bytes = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
wasmcloud-interface-keyvalue = { workspace = true }
wasmbus-rpc = { workspace = true, features = ["otel"] }

# test dependencies
[dev-dependencies]
wasmcloud-test-util = { workspace = true }
rand = { workspace = true }

[[bin]]
name = "kvredis"
path = "src/main.rs"
