[package]
name = "wasmcloud-provider-blobstore-fs"
version = "0.2.1"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
atty = { workspace = true }
base64 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
wasmbus-rpc = { workspace = true, features = ["otel"] }
wasmcloud-interface-blobstore = { workspace = true }

# test dependencies
[dev-dependencies]
futures-util = { workspace = true }
tokio = { workspace = true, features = [ "full" ] }
wasmcloud-provider-blobstore-fs = { path = ".", artifact = "bin" }
wasmcloud-test-util = { workspace = true }

[[bin]]
name = "blobstore_fs"
path = "src/main.rs"
