name: blobstore-fs

on:
  pull_request:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-linux:
    strategy:
      matrix:
        platform:
        - target: aarch64-apple-darwin
          host: macos-12
          install-path: /bin/blobstore_fs

        - target: aarch64-unknown-linux-musl
          host: ubuntu-22.04
          install-path: /bin/blobstore_fs

        - target: armv7-unknown-linux-musleabihf
          host: ubuntu-22.04
          install-path: /bin/blobstore_fs

        - target: x86_64-apple-darwin
          host: macos-12
          install-path: /bin/blobstore_fs

        - target: x86_64-pc-windows-gnu
          host: ubuntu-22.04
          install-path: /bin/blobstore_fs.exe

        - target: x86_64-unknown-linux-musl
          host: ubuntu-22.04
          install-path: /bin/blobstore_fs

    name: blobstore-fs-${{ matrix.platform.target }}
    runs-on: ${{ matrix.platform.host }}
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/install-nix
      with: 
        cachixAuthToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - uses: ./.github/actions/build-nix
      with:
        package: wasmcloud-provider-blobstore-fs-${{ matrix.platform.target }}
        install-path: ${{ matrix.platform.install-path }}
    - run: ${{ matrix.platform.test-bin }}
    - uses: ./.github/actions/build-nix
      with:
        package: wasmcloud-provider-blobstore-fs-${{ matrix.platform.target }}-oci
    - run: ${{ matrix.platform.test-oci }}

  cargo:
    strategy:
      matrix:
        check:
        - fmt
        - clippy
        - nextest

    name: cargo ${{ matrix.check }}
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/install-nix
      with: 
        cachixAuthToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build -L .#checks.x86_64-linux.${{ matrix.check }}
