name: doc

on:
  workflow_dispatch:
  push:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 1 # abort caching attempt if it's slow

permissions:
  contents: write

jobs:
  doc:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - run: sudo mkdir -p /nix
    - run: sudo chown $(whoami) /nix
    - uses: actions/cache@v3
      with:
        path: /nix
        key: nix
    - uses: nixbuild/nix-quick-install-action@v21
      with:
        nix_conf: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ github.token }}
          substituters = https://cache.nixos.org https://cache.garnix.io
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=
    - uses: cachix/cachix-action@v12
      continue-on-error: true
      with:
        name: wasmcloud
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build -L .#checks.x86_64-linux.doc
    - run: tar xf ./result/target.tar.zst
    - name: Write `.nojekyll`
      uses: DamianReeves/write-file-action@v1.2
      with:
        path: .nojekyll
        write-mode: overwrite
        contents: ""
    - name: Write `index.html`
      uses: DamianReeves/write-file-action@v1.2
      with:
        path: .nojekyll
        write-mode: overwrite
        contents: |
          <!DOCTYPE html>
          <meta charset="utf-8">
          <title>Redirecting to wasmcloud/index.html</title>
          <meta http-equiv="refresh" content="0; URL=wasmcloud/index.html">
          <link rel="canonical" href="https://${{ github.repository.owner }}.github.io/wasmCloud/wasmcloud/index.html">
    - uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        folder: target/doc
        clean: true
